apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shepard
  labels:
    app.kubernetes.io/name: shepard
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shepard
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shepard
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "registry.gitlab.com/dlr-shepard/backend"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
          env:
            - name: CATALINA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: catalinaOpts
            - name: OIDC_PUBLIC
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: oidcPublic
            - name: OIDC_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: oidcAuthority
            - name: INFLUX_HOST
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: influxHost
            - name: INFLUX_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: influxUsername
            - name: INFLUX_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: influxPassword
            - name: NEO4J_HOST
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: neo4jHost
            - name: NEO4J_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: neo4jUsername
            - name: NEO4J_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: neo4jPassword
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: mongoHost
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: mongoUsername
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: shepard
                  key: mongoPassword
      serviceAccountName: default-shepard