---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/component: "keycloak"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "keycloak"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/component: "keycloak"
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:19.0.2
          imagePullPolicy: Always
          args:
            - "start-dev"
            - "--import-realm"
          env:
            # Kustomization overrides the first value, so KC_HOSTNAME must be on Index 0
            - name: KC_HOSTNAME_URL
              value: "http://keycloak.auth.svc.cluster.local:8080"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "b5JVMMrU-xwYj-y78d-ZyHX-4gdBYQhH7xuC"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  key: jdbc-uri
                  name: keycloak-db-pguser-keycloak
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_CACHE
              value: ispn
            - name: KC_CACHE_STACK
              value: kubernetes
            - name: JAVA_OPTS_APPEND
              value: "-Djgroups.dns.query=keycloak-discovery"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-volume
          livenessProbe:
            exec:
              command:
                - curl
                - --head
                - --fail
                - --silent
                - http://127.0.0.1:8080/health/live
            initialDelaySeconds: 20
            periodSeconds: 2
            failureThreshold: 150
          readinessProbe:
            exec:
              command:
                - curl
                - --head
                - --fail
                - --silent
                - http://127.0.0.1:8080/health/ready
            initialDelaySeconds: 20
            periodSeconds: 2
            failureThreshold: 250
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/component: "keycloak"
    app.kubernetes.io/instance: "keycloak-http"
spec:
  selector:
    app.kubernetes.io/component: "keycloak"
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-discovery
  labels:
    app.kubernetes.io/component: "keycloak"
    app.kubernetes.io/instance: "keycloak-discovery"

spec:
  selector:
    app.kubernetes.io/component: "keycloak"
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
  type: ClusterIP
---