apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

configMapGenerator:
  - name: keycloak-configmap
    behavior: create
    files:
      - os4ml-realm.json # TODO: Realm mit secrets austauschen

resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml