apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argocd/config/base
    directory:
      recurse: true
      exclude: applications/shepard.yaml
    repoURL: https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s