apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - regcred.yaml
  - github.com/argoproj/argo-cd.git/manifests/cluster-install?ref=v2.12.0
  - default-application.yaml

patchesStrategicMerge:
  - argocd-secret.yaml
  - argocd-cmd-params-cm.yaml
patches:
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /imagePullSecrets
        value: [name: regcred]
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yaml
  - target:
      kind: ConfigMap
      name: argocd-ssh-known-hosts-cm
    path: argocd-ssh-known-hosts-cm.yaml
