apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWItcmVnaXN0cnkud29ncmEuY29tIjp7InVzZXJuYW1lIjoicmVhZF9yZWdpc3RyeSIsInBhc3N3b3JkIjoiZ2xwYXQtakZIWXhzdkw4WDF6UVI5ZHkzazYiLCJhdXRoIjoiY21WaFpGOXlaV2RwYzNSeWVUcG5iSEJoZEMxcVJraFplSE4yVERoWU1YcFJVamxrZVROck5nPT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: argocd
type: kubernetes.io/dockerconfigjson
