apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWItcmVnaXN0cnkud29ncmEuY29tIjp7InVzZXJuYW1lIjoicmVhZF9yZWdpc3RyeSIsInBhc3N3b3JkIjoiZ2xwYXQtaGs3QkVlYVRQNmpaeFF4NlRudkYiLCJhdXRoIjoiY21WaFpGOXlaV2RwYzNSeWVUcG5iSEJoZEMxb2F6ZENSV1ZoVkZBMmFscDRVWGcyVkc1MlJnPT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: argocd
type: kubernetes.io/dockerconfigjson
