apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWItcmVnaXN0cnkud29ncmEuY29tIjp7InVzZXJuYW1lIjoicmVhZF9yZWdpc3RyeSIsInBhc3N3b3JkIjoiZ2xwYXQtRTQ4RWpWRGN6d1otdHJIOVdoRUQiLCJhdXRoIjoiY21WaFpGOXlaV2RwYzNSeWVUcG5iSEJoZEMxRk5EaEZhbFpFWTNwM1dpMTBja2c1VjJoRlJBPT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: argocd
type: kubernetes.io/dockerconfigjson
