apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shepard
  labels:
    app.kubernetes.io/name: shepard
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: shepard
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP