apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - github.com/CrunchyData/postgres-operator-examples.git/kustomize/install/namespace?ref=main
  - github.com/CrunchyData/postgres-operator-examples.git/kustomize/install/default?ref=main
