apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: shepard-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "shepard.os4ml.wogra.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: shepard-ingress-cert
      hosts:
        - "shepard.os4ml.wogra.com"