apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: cluster-config
      namespace: argocd
    patch: |-
      - op: remove
        path: /spec/source/directory/exclude
