apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - deny-all-authorizationpolicy.yaml
  - envoy-filter-kubeflow-userid.yaml
  - gateway-authorizationpolicy.yaml
  - kubeflow-cluster-roles.yaml
