apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
  - github.com/kubeflow/manifests.git/apps/pipeline/upstream/cluster-scoped-resources?ref=v1.6.0
  - registry-credentials.yml
