apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - registry-credentials.yml
  - github.com/argoproj-labs/argocd-image-updater.git/manifests/base?ref=v0.12.0
patchesStrategicMerge:
  - configuration.yaml
patches:
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /imagePullSecrets
        value: [name: registry-credentials]