apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubeflow/manifests.git/apps/pipeline/upstream/env/platform-agnostic-emissary?ref=v1.6.1
namespace: kubeflow

patches:
  - target:
      kind: PersistentVolumeClaim
      version: v1
      name: minio-pvc
      namespace: kubeflow
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi