apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-replica
spec:
  replicas: 2 
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: redis-replica
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: redis-replica
    spec:
      containers:
      - name: redis
        image: redis:7.0.5-alpine
        command:
          - "redis-server"
        args:
          - "--slaveof"
          - "master.redis.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"   
        ports:
          - name: redis
            containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
