apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: redis
spec:
  selector:
    app: redis
    name: redis-master
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      name: redis
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: replica
  namespace: redis
spec:
  selector:
    app: redis
    name: redis-replica
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      name: redis
      protocol: TCP
