apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: minio-gateway
  namespace: minio-tenant
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "*"