kind: Secret
apiVersion: v1
metadata:
  name: oauth2-proxy
  namespace: auth
stringData:
  client-id: kubeflow-oidc-authservice
  client-secret: 5lmVYeVcjOIXkuMr3l2PqUlA4zKp3wkY
  cookie-secret: hLky-wmSha1Kcn-R50S5AUZSK-JyNjL_fyPwRPvLI98= # TODO SECRETS ÄNDERN