apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cert-manager
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.8.2
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
