apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: kubeflow
  source:
    repoURL: 'https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git'
    path: manifests/kubeflow/common/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: kubeflow
  source:
    repoURL: 'https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git'
    path: manifests/kubeflow/components/pipelines-standalone/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---