apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: shepard
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 13.1.5
    helm:
      parameters:
        - name: auth.password
          value: shepard1234
        - name: auth.username
          value: mongodb-shepard
        - name: auth.rootPassword
          value: admin1234
        - name: auth.database
          value: admin
    chart: mongodb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shepard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: shepard
  source:
    repoURL: 'https://helm.neo4j.com/neo4j'
    targetRevision: 4.4.11
    helm:
      values: |-
        neo4j:
          password: "Neo4j1234"
          edition: "community"
          acceptLicenseAgreement: "yes"
          resources:
            cpu: "500m"
            memory: "2Gi"

        volumes:
          data:
            mode: "defaultStorageClass"

        config:
          dbms.default_database: "neo4j"
          dbms.config.strict_validation: "true"

        services:
          neo4j:
            enabled: false
            spec:
              type: ClusterIP
    chart: neo4j-standalone
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shepard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: shepard
  source:
    repoURL: 'https://helm.influxdata.com'
    targetRevision: 4.12.0
    helm:
      parameters:
        - name: setDefaultUser.user.username
          value: admin
      values: |-
        setDefaultUser:
          enabled: true
          user:
            username: "admin"
            password: "influx1234"
    chart: influxdb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shepard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shepard-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: shepard
  source:
    repoURL: 'https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git'
    path: manifests/shepard/common/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shepard-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: shepard
  source:
    repoURL: 'https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git'
    path: manifests/shepard/backend/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shepard-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: shepard
  source:
    repoURL: 'https://github.com/WOGRA-AG/terraform-kustomization-os4ml.git'
    path: manifests/shepard/frontend/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s